[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "random"]
set = true

[templates.hyperland]
input_path = '~/.config/theme/hyprland.conf'
output_path = '~/.config/hypr/color.conf'
post_hook = 'hyprctl reload'

[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'omarchy-restart-waybar'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'omarchy-restart-terminal'


[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.starship]
input_path = './templates/starship-colors.toml'
output_path = '~/.config/starship.toml'
